### ISSUE TITLE
Move comments from template should be cleaned up and removed to requirement

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/package-validator#108]

**Comment by gep13** [comment]
@ferventcoder can you define "cleaned up" please?

**Comment by ferventcoder** [comment]
Our current guideline about comments needs to be moved to a requirement.

**Comment by gep13** [comment]
Ok, seems like we are on the same page.  I read `cleaned up and removed to requirement` as do some stuff, and then move to a requirement.  Rather than simply move guideline to requirement.
