### ISSUE TITLE
Only Validate Chocolatey Automation Scripts

### ISSUE THREAD

**Issue by splatteredbits** [chocolatey/package-validator#147]
Original title: MoreThanMaximumAutomationScripts Fails PowerShell Module Packages

I have Chocolately package, [Carbon](https://chocolatey.org/packages/carbon), for a PowerShell module. It contains a _lot_ of PowerShell scripts/files. Because of this, it fails the MoreThanMaximumAutomationScripts rule. Please update this rule to only check the Tools directory.

**Comment by ferventcoder** [comment]
Thanks for logging this!

**Comment by ferventcoder** [comment]
This is being completed now.

**Comment by ferventcoder** [comment]
This is done.
