### ISSUE TITLE
There is no package to validate

### ISSUE THREAD

**Issue by carolynvs** [chocolatey/package-validator#149]
My package seems to have hit a bug in the validator which is preventing it from being approved/listed.

```
Something went very wrong. There is no package to validate. Please contact the site admins for next steps.
```

This is the stuck version: https://chocolatey.org/packages/carina/1.5.0

**Comment by ferventcoder** [comment]
It means there was an issue when you pushed the package. It basically doesn't exist on our servers and you should repush it again. HTH, and we probably need to update that message.

**Comment by ferventcoder** [comment]
Added
