### ISSUE TITLE
Fails to clone single branch

### ISSUE THREAD

**Issue by MrHinsh** [chocolatey/package-validator#150]
Guys,

 When running `git tfs clone "http://tfsserver:8080/tfs/ProductionTPC/" "$/TeamProject/Main" OFM-Git --branches=none --debug` I only get the first folder in the branch listed. There were a lot of early renames of branches. Is there a way to filter to only pull from a specified changeset forward?

-MrHinsh

**Comment by ferventcoder** [comment]
Guessing this didn't apply to the validator?

**Comment by MrHinsh** [comment]
I am not sure I understand your response @ferventcoder

**Comment by ferventcoder** [comment]
you opened this issue and then promptly closed it... it doesn't appear that the issue applies to this repository (the validator). So I'm guessing that is why you closed it?

**Comment by MrHinsh** [comment]
Got it... yea... I had too many windows open :)
