### ISSUE TITLE
PackageIdTooLongWithNoDashes wiki still empty

### ISSUE THREAD

**Issue by brandonh-msft** [chocolatey/package-validator#151]
https://github.com/chocolatey/package-validator/wiki/PackageIdTooLongWithNoDashes

is being linked to in review e-mails:

> •	If this is a brand new package that has never went through approval before, the reviewer will suggest a change to the package id. [More...](https://github.com/chocolatey/package-validator/wiki/PackageIdTooLongWithNoDashes)

but the page is still blank.

**Comment by ferventcoder** [comment]
Thanks, filing an issue works better than the stub suggestions - https://github.com/chocolatey/package-validator/wiki/PackageIdTooLongWithNoDashes
