### ISSUE TITLE
Requirement: Restrict FossHub downloading

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/package-validator#153]
FossHub has recently expressed a desire not to have community packages download software from their site. 

Detect this and disallow it.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub

**Comment by gep13** [comment]
@ferventcoder should/can we add a check on the package for a dependency on the fosshub extension?

**Comment by ferventcoder** [comment]
I don't think it is necessary. If you look at the test, it shows that it still works just fine in detection.

**Comment by gep13** [comment]
Okay dokay
