### ISSUE TITLE
Invalid CLA link

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/package-validator#158]
The [Sign the Contributor License Agreement](https://www.clahub.com/agreements/chocolatey/package-validator) link ini the [CONTRIBUTING.md](https://github.com/chocolatey/package-validator/blob/master/CONTRIBUTING.md) file is invalid.

**Comment by gep13** [comment]
@ferventcoder do we have a standalone CLA for the package validator, or should it point to the same one as for chocolatey itself?

**Comment by ferventcoder** [comment]
Whoops. Yeah, definitely.

**Comment by ferventcoder** [comment]
We maybe should remove it for now. It's really necessary for Chocolatey/Choco, not so much something like validator. Great to have noticed that.
