### ISSUE TITLE
[Requirement] Links must actually go to an existing url

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/package-validator#160]

**Comment by mkevenaar** [comment]
I would suggest that the package validator requires that all URLs in the nuspec file (e.g. docsUrl, mailinglistUrl) result in a valid HTTP status (2xx, 3xx). A 500 might be considered as a warning, as there  could be something wrong with the remote server. Take a look at [this page](https://www.restapitutorial.com/httpstatuscodes.html) for more status codes.

**Comment by mkevenaar** [comment]
@gep13 the changes you have merged do not validate URL inside markdown fields. Do you still want that?

**Comment by gep13** [comment]
@mkevenaar yes, I think that would make sense.

**Comment by mkevenaar** [comment]
@gep13 I have opened #196 for this.

**Comment by pauby** [comment]
While I was putting together [chocochecks](https://github.com/pauby/chocochecks/) I came across issues where valid URL's were actually being flagged as 404's. They work fine in the browser but not using, in my case, `Invoke-WebRequest`.

What reminded me to come and post this here was [this in Gitter](https://gitter.im/chocolatey/chocolatey.org?at=5e064fdad31dba03fdb5c2c9)
