### ISSUE TITLE
[Note?] Add `.extension`,`.template` to valid suffixes

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/package-validator#163]
As the title suggest, adding the `.extension` suffix as a valid suffix (along with `.portable` and `.install`).
Or perhaps change the validation message to something like *The .extension` suffix have been used, please make sure that the package is an extension of chocolatey or another package*

It's nothing major, it's just that it is annoying as it currently is.

**Comment by ferventcoder** [comment]
Yes, there are a few more valid suffixes that are known. We should definitely be sure all of them are allowed.

**Comment by AdmiringWorm** [comment]
what are the other suffixes?
I found one other `.template` (excluding `.app` and `.commandline` as they shouldn't be used anymore).
