### ISSUE TITLE
AdminTagShouldBeIncludedWhenUsingAdminHelpersGuideline appears to be matching substrings

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/package-validator#168]
I think the code will match `Uninstall-ChocolateyPackage` when searching for `install-ChocolateyPackage`.

The uninstall function is not listed as requiring admin permission

**Comment by AdmiringWorm** [comment]
Looking at the source that would indeed be true as it seem to only check if the script contains `install-chocolateypackage`.
https://github.com/chocolatey/package-validator/blob/master/src/chocolatey.package.validator/infrastructure.app/rules/AdminTagShouldBeIncludedWhenUsingAdminHelpersGuideline.cs#L41

Still, I personally think that a match for `Uninstall-ChocolateyPackage` should require the admin tag though.

**Comment by ferventcoder** [comment]
This one is being removed as a requirement, so this should not come up.

**Comment by ferventcoder** [comment]
#169
