### ISSUE TITLE
Typo in the VERFICATION word

### ISSUE THREAD

**Issue by rgl** [chocolatey/package-validator#173]
There's an typo in VERFICATION word at https://github.com/chocolatey/package-validator/blob/8c14526f5ee5a60aa2badbcbb28d00f9a16459f1/src/chocolatey.package.validator/infrastructure.app/rules/VerficationFileMissingWhenBinariesAreIncludedRequirement.cs#L27.

The variable names in the C# code also have that typo.

**Comment by ferventcoder** [comment]
Thanks for noting that, a fix has been merged for it.
