### ISSUE TITLE
Incorrect URL in rule

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-validator#187]
In this rule:

https://github.com/chocolatey/package-validator/blob/master/src/chocolatey.package.validator/infrastructure.app/rules/CopyRightAndAuthorFieldsShouldntContainEmailRequirement.cs

It links to this URL:

https://github.com/chocolatey/package-validator/wiki/CopyrightAndAuthorFieldsShouldntContainEmail

However, this URL doesn't exist.  Instead, it should point to the following URL:

https://github.com/chocolatey/package-validator/wiki/NuspecDoesNotContainEmail

**Comment by AdmiringWorm** [comment]
The PackageIdUsesUnderscoreNotes rule also links to a page that doesn't exist.

https://github.com/chocolatey/package-validator/blob/master/src/chocolatey.package.validator/infrastructure.app/rules/PackageIdUsesUnderscoresNote.cs

Links to:
https://github.com/chocolatey/package-validator/wiki/PackageIdUsesUnderscores

Can't find a wiki page that matches that rule either.

**Comment by mkevenaar** [comment]
I have fixed the URL for the `CopyRightAndAuthorFieldsShouldntContainEmailRequirement.cs` file. 

I think we need to create a new wiki document for the `PackageIdUsesUnderscoresNote.cs` file (https://github.com/chocolatey/package-validator/wiki/PackageIdUsesUnderscores)

**Comment by gep13** [comment]
>@mkevenaar said...
I think we need to create a new wiki document for the PackageIdUsesUnderscoresNote.cs

I have created a stub page in the wiki for this.
