### ISSUE TITLE
Requirement: Flag the use on invalid markdown headers

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-validator#194]
This is related to an issue that was raised on the chocolatey.org repository here:

https://github.com/chocolatey/chocolatey.org/issues/772

Primarily, this should check the Description field, but I given that the Release Notes section can also contain markdown, it would make sense to also include that field in the check as well.

**Comment by ferventcoder** [comment]
@gep13 make it a requirement. It should be easy enough to fix.
