### ISSUE TITLE
Valid URLs have failed automated validation on i2p package

### ISSUE THREAD

**Issue by TakataSanshiro** [chocolatey/package-validator#224]
https://chocolatey.org/packages/i2p

> i2p has failed automated validation.
> Requirements
> The DocsUrl element in the nuspec file should be a valid Url. Please correct this More...
> The LicenseUrl element in the nuspec file should be a valid Url. Please correct this More...
> The ProjectUrl element in the nuspec file should be a valid Url. Please correct this More...
> The ProjectSourceUrl element in the nuspec file should be a valid Url. Please correct this More...

**Comment by gep13** [comment]
@TakataSanshiro apologies for not getting back to you sooner about this.

Checking the logs for this package when going through the package-validator, we see the following:

![image](https://user-images.githubusercontent.com/1271146/75631391-2a4cae80-5bb8-11ea-8032-bcce82ebc99c.png)

However, I don't think that this is a timeout issue, but rather something else.  When I try to access the home page on my own machine:

https://geti2p.net

It works just mine, and likely works just fine for you too.  However, when I try to open the site on the browser on the machine where the validation is being done, I get the following:

![image](https://user-images.githubusercontent.com/1271146/75631442-8dd6dc00-5bb8-11ea-8217-4db12f496078.png)

At this point in time, I have no real clue why these URL's aren't working from this machine.  I am open to any ideas that you might have.

**Comment by TakataSanshiro** [comment]
I can connect to the website on IE on my own chocolatey test environment even "Internet Explorer Enhanced Security Configuration" is enabled.

It might cause of DNS filterings on the test machine, but it can download the installer. That's weird.

Or your test machine's ISP DNS routing problem.
I don't know BGP routing well.
Refer to this page.
https://serverfault.com/questions/597703/my-site-cant-be-accessed-from-certain-isps

> This seems to be a routing problem. Ask them to traceroute your server's IP, and ask them to ask their ISP what's going on.


If your machine and the test machine were using the same ISP, then not a DNS routing problem.

**Comment by TakataSanshiro** [comment]
I don't know why, but the new version of i2p has passed automated validation..
https://chocolatey.org/packages/i2p/0.9.45

**Comment by gep13** [comment]
@TakataSanshiro thanks for getting back to me about this!

No idea how/why this started working, but I am glad that it has.  I will close off this issue for now.
