### ISSUE TITLE
WhatsApp package is failing URLs when they appear to be valid

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/package-validator#226]
https://chocolatey.org/packages/WhatsApp/0.4.1299 is failing validation

> WhatsApp has failed automated validation.
> Requirements
> 
> Requirements represent the minimum quality of a package that is acceptable. When a package version has failed requirements, the package version requires fixing and/or response by the maintainer. Provided a Requirement has flagged correctly, it must be fixed before the package version can be approved. The exact same version should be uploaded during moderation review.
> 
>     The DocsUrl element in the nuspec file should be a valid Url. Please correct this More...
>     The BugTrackerUrl element in the nuspec file should be a valid Url. Please correct this More...
>     The LicenseUrl element in the nuspec file should be a valid Url. Please correct this More...
>     The ProjectUrl element in the nuspec file should be a valid Url. Please correct this More...
>     The MailingListUrl element in the nuspec file should be a valid Url. Please correct this More...
> 
> Guidelines
> 
> Guidelines are strong suggestions that improve the quality of a package version. These are considered something to fix for next time to increase the quality of the package. Over time Guidelines can become Requirements. A package version can be approved without addressing Guideline comments but will reduce the quality of the package.
> 
>     In the ReleaseNotes element of the nuspec file a potentially invalid Url has been found. Recommendation is to fix this URL

Here's the nuspec source

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>WhatsApp</id>
    <version>0.4.930</version>
    <title>WhatsApp Messenger</title>
    <authors>WhatsApp Inc.</authors>
    <owners>sippi</owners>
    <licenseUrl>https://www.whatsapp.com/legal</licenseUrl>
    <projectUrl>http://www.whatsapp.com</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/sippi90/chocolateyautomaticpackages/master/icons/whatsapp.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>WhatsApp Messenger is available for iPhone, BlackBerry, Android, Windows Phone and Nokia and yes, those phones can all message each other! Because WhatsApp Messenger uses the same internet data plan that you use for email and web browsing, there is no cost to message and stay in touch with your friends. In addition to basic messaging WhatsApp users can create groups, send each other unlimited images, video and audio media messages.</description>
    <summary>WhatsApp Messenger is a cross-platform mobile messaging app which allows you to exchange messages without having to pay for SMS</summary>
    <copyright>© 2020 WhatsApp Inc.</copyright>
    <tags>messenger chat windows client admin</tags>
    <packageSourceUrl>https://github.com/sippi90/chocolateyautomaticpackages/tree/master/WhatsApp</packageSourceUrl>
    <docsUrl>https://faq.whatsapp.com/</docsUrl>
	<bugTrackerUrl>https://blog.whatsapp.com/</bugTrackerUrl>
	<releaseNotes>https://blog.whatsapp.com/</releaseNotes>
    <mailingListUrl>https://www.whatsapp.com/contact/</mailingListUrl>
  </metadata>
   <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
```

**Comment by gep13** [comment]
@flcdrg this has now been taken care of.  Apologies for the delay in getting to this.
