### ISSUE TITLE
Automated validation: timeout issue on URL

### ISSUE THREAD

**Issue by chtof** [chocolatey/package-validator#229]
https://chocolatey.org/packages/eclipse-java-oxygen/2020.03:
_eclipse-java-oxygen has failed automated validation.
(...)
The ProjectSourceUrl element in the nuspec file should be a valid Url. Please correct this_

ProjectSourceUrl: https://git.eclipse.org/c

The project source URL is available so I think it's a timeout issue (the timeout was increased some time ago by Chocolatey Team but not sure if it has been applied on all URL tags). I have had this same issue with another package one or two day ago, I will post more information if I found the name of the another package.

**Comment by chtof** [comment]
Same issue also for:
- https://chocolatey.org/packages/clipto-pro.install/2.4.6.20200318
_The MailingListUrl element in the nuspec file should be a valid Url. Please correct this_
Software mailing list: https://www.reddit.com/user/CliptoPro

**Comment by chtof** [comment]
https://chocolatey.org/packages/klog/1.0
*The MailingListUrl element in the nuspec file should be a valid Url. Please correct this*
Software mailing list: https://www.klog.xyz/mailing-lists/

**Comment by AdmiringWorm** [comment]
Having the same problem with the [audacity package](https://chocolatey.org/packages/audacity/2.3.3), it mentions invalid URLs for `DocsUrl`, `LicenseUrl` and `ProjectUrl`.

All three of these URLs are valid though:
https://www.audacityteam.org/help/documentation
https://audacityteam.org/about/license#license
https://audacityteam.org/

/CC @gep13 @pauby

**Comment by gep13** [comment]
@chtof @AdmiringWorm I believe everything has been taken care of here, so going to close this out.  Let me know if you have any follow up comments.
