### ISSUE TITLE
URL failing validation

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/package-validator#232]
In the [wsus-offline-update](https://chocolatey.org/packages/wsus-offline-update/12.0) package, the [projectSourceUrl](https://trac.wsusoffline.net/browser/trunk) is failing validation. 

However, I can access it in both Firefox and Chrome. 

I am removing it as a workaround for the moment.

**Comment by gep13** [comment]
@TheCakeIsNaOH apologies for not getting back to you about this until now!

Looking at the site, I am going to say that this was being caused by a time out issue, and it would appear that this has now passed validation successfully.

As such, I am going to close off this ticket.
