### ISSUE TITLE
Grafana URLs failing

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/package-validator#242]
https://chocolatey.org/packages/grafana/7.2.0

The DocsUrl element in the nuspec file should be a valid Url. Please correct this More...
The ProjectUrl element in the nuspec file should be a valid Url. Please correct this More...

Docs: http://docs.grafana.org/
Project: https://grafana.com/

**Comment by gep13** [comment]
Related to this issue: https://github.com/chocolatey/package-validator/issues/243

**Comment by mkevenaar** [comment]
@gep13 also this one:

https://chocolatey.org/packages/lastpass/4.57.1
DocsUrl: https://helpdesk.lastpass.com/

**Comment by mkevenaar** [comment]
Grafana 7.2.1 is also failing: https://chocolatey.org/packages/grafana/7.2.1

**Comment by gep13** [comment]
@mkevenaar this problem was addressed by the changes that were made in #243 

All the grafana packages are now through package validator.
