### ISSUE TITLE
Restic ProjectUrl failing

### ISSUE THREAD

**Issue by CRBroughton** [chocolatey/package-validator#244]
I'm trying to download the latest version of Restic, but the projecturl seems to not want to work, despite it being correct?

https://chocolatey.org/packages/restic/0.9.6

Edit: It seems to work if I ask for the latest version specifically with `choco install --version=0.9.6`

Also sorry for accidentally closing the issue, still getting used to github.

**Comment by AdmiringWorm** [comment]
> Edit: It seems to work if I ask for the latest version specifically with choco install --version=0.9.6

When a package version haven't been approved, you will always need to specify the version.

The project URL that you mention have nothing to do with the actual installation of the package, it is the metadata for the issue (I see that it is valid though, so this needs to be looked into by the chocolatey staff).

[URL in question: `https://www.restic.net/`](https://www.restic.net/)

**Comment by gep13** [comment]
@CRBroughton @AdmiringWorm this has been addressed with the fix from #243 and the package is now successfully passing package validator.  Going to mark this as a duplicate.
