### ISSUE TITLE
geogebra6 DocsUrl fails during "Validation testing"

### ISSUE THREAD

**Issue by chtof** [chocolatey/package-validator#245]
https://chocolatey.org/packages/geogebra6/6.0.608.0

The DocsUrl element in the nuspec file should be a valid Url

DocsUrl is available, https://wiki.geogebra.org/en/Manual

When an URL is seen as available, **could you adapt your script to check a second time or increase the timeout**?

Can't launch a rerun as "verification testing pending".

**Comment by gep13** [comment]
@chtof apologies for only getting to this now...

I has just re-ran package validation (without making any changes to the package validator) and it went through without any issues.

I am going to close this out, but please feel free to reach out if you are seeing issues with other package validation attempts.
