### ISSUE TITLE
docsUrl for latest version of zotero is failing

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/package-validator#246]
Another package that seems to be affected by the validation of package URLs is the latest version of [zotero](https://chocolatey.org/packages/zotero/5.0.91).

The documentation URL takes a bit long sometimes to view, so I assume there is a timeout on the validator due to this.

However, the URL is still valid.

**Comment by gep13** [comment]
@AdmiringWorm I have just re-run the package validator on this package, and all URL's contained within it have validated correctly.

I can only assume that this was a glitch in the matrix.

Going to close this out.
