### ISSUE TITLE
caddy docsUrl failing

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/package-validator#247]
https://chocolatey.org/packages/caddy/2.2.0

**Comment by gep13** [comment]
@majkinetor I am digging into what is going on here just now, and I believe I have found out what the problem is.  Should have a new version of package-validator deployed soon, and I will push your package through moderation process.

**Comment by gep13** [comment]
The docsUrl in this package is:

```
https://caddyserver.com/docs
```

In the browser, this causes a 308 permanent redirect to:

```
https://caddyserver.com/docs/
```

The .Net HttpClient doesn't understand the 308 Status Code until .Net Core 2.1:

https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netcore-2.1

As a result, we will handle any response that include a `ReasonPhrase` of `Permanent Redirect` as a valid URL.

**Comment by gep13** [comment]
@majkinetor this change has been released, and the caddy package is now successfully passing URL validation.
