### ISSUE TITLE
[Bug] PackageSourceUrl fails on multiple packages, but the links are OK

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey/package-validator#249]
Here are the packages that have received the error, but the link is OK and are on github
Maybe linked to the TLS1.2 ?
- [Freeplane](https://chocolatey.org/packages/FreePlane/1.8.9)
- [Procdump](https://chocolatey.org/packages/procdump/10.00)

Thank you

**Comment by gep13** [comment]
@tunisiano187 I don't see any issues with URL's on the Freeplane package, and the URL for the Procdump package is pointing at an invalid URL (it is still pointing that the dtgm repository) and will need to be updated.

As such, I don't believe there is anything that needs to be done here.
