### ISSUE TITLE
Update rule information URLs to use docs.chocolatey.org

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-validator#250]
All the rule information that currently exists here:

https://github.com/chocolatey/package-validator/wiki

Has been ported over to here:

https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/

The links inline the code base need to be updated to reflect these new locations.

**Comment by gep13** [comment]
@pauby can you let me know when this is deployed, and update the label to indicate that it is live?  Thanks

**Comment by pauby** [comment]
@gep13 This is live now.
