### ISSUE TITLE
Requirement: Validate that all Url's go "somewhere"

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-validator#26]
i.e. don't lead to a 404.

**Comment by gep13** [comment]
@ferventcoder thoughts on this one? Requirement, note, guideline, suggestion

**Comment by ferventcoder** [comment]
This could be considered a duplicate of #18.

**Comment by ferventcoder** [comment]
But requirement.

**Comment by gep13** [comment]
Agreed, this is a duplicate. Will close in favour of existing one.
