### ISSUE TITLE
Requirement: Never call InstallationArguments environment variable

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/package-validator#29]
Suggest using package parameters instead.

Had a package once that removed install args and put them back once it was done.

**Comment by gep13** [comment]
@ferventcoder I am going to work on the assumption that it is all three of these:

https://github.com/chocolatey/choco/blob/0ec22c8cfa5d71933fc2a378ddee62d195f8199b/src/chocolatey/infrastructure.app/services/PowershellService.cs#L179-L181
