### ISSUE TITLE
Add All Required Rules

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-validator#3]
These are taken in part from here:

https://github.com/chocolatey/choco/wiki/Moderation

The following is a list of rules that need to be added, and these will be updated as they are implemented.  New rules can be added here as they are thought of.

## Requirements
- [x] Copyright Word Count Minimum
- [x] Description
- [x] Install Automation Script Named Correctly
- [x] License Url Missing When License Acceptance True
- [x] Package Internal Files Are Not Packaged 
- [x] Portable Package Scripts Do Not Use Program Files
- [x] Project Url
- [x] Scripts Do Not Contain Choco Commands
- [x] Scripts Do Not Contain Internal Variables
- [x] Source Control Internal Files Are Not Packaged
- [x] Tags Are Spaced Separated
- [x] Tags Do Not Contain Chocolatey
- [x] Uninstall Automation Script Named Correctly
- [x] Install and Uninstall Scripts work with PowerShell V2, see #1 
- [x] Templated Comments have been removed
- [x] UTF-8 Encoding is being used
- [x] ~~Correct BOM at start of file~~ - **NOTE** - not a fan of this one, we actually want this to be UTF-8 w/out BOM

## Guidelines
- [x] Description Word Count Minimum 30
- [x] License Url Does Not Match Project Url
- [x] License Url Missing
- [x] Package Source Url Missing
- [x] Project source Url Does Not Match Project Url
- [x] Project Source Url Missing
- [x] Summary Not Empty
- [x] Tags Not Empty
- [x] Title Not Empty
- [x] Title Not Same As Package Id
- [x] Does the download include both x86 and x64 urls if available? - see https://github.com/chocolatey/package-validator/issues/17
- [x] Icon Url Missing
- [x] Release Notes Not Empty
- [x] Write-ChocolateySuccess / Write-ChocolateyFailure
- [x] request admin tag if it calls Install-ChocolateyPackage (or uses another admin script)

## Suggestions
- [x] Bug Tracker Url Missing
- [x] Docs Url Missing
- [x] Mailing List Url Missing
- [x] With Get-BinRoot, ask if the user should move to a simpler approach

## Notes
- [x] Binaries are included
- [x] Package Id Uses Dots
- [x] Author Field Is Not Used For Maintainer

## Things that require more thought
- [x] check package name - flag if first version based on the naming convention (doesn't matter if prerelease or not)
- [x] suggest the name split if over 25 chars with no -
- [x] flag on "."" in name (unless .portable/.install)

## Things that can't be automated - These have now been covered in the moderation instructions https://github.com/chocolatey/choco/wiki/Moderation
- [x] Verify description contains Trial information, when required
- [x] Trial software should include #trial tag
- [x] Licensed software should include #license
- [x] Does the download version match the package version?
- [x] Does the package try to do anything that an existing Chocolatey function already covers? The maintainers would need a really good reason for diverging from that.
- [x] Not a package duplicating another existing package

Implements https://github.com/chocolatey/chocolatey.org/issues/181

**Comment by ferventcoder** [comment]
BOM may not be there if the encoding is UTF-8 w/out BOM (and that is actually preferred).

**Comment by ferventcoder** [comment]
> Does the download include both x86 and x64 urls if available?

This is probably going to end up in a note, unless you can think of a way to detect (perhaps if url includes x86 or 32). Then we could also add a note.

**Comment by ferventcoder** [comment]
> Install and Uninstall Scripts work with PowerShell V2, see #1

This one is interesting and I have some ideas for it. :)

**Comment by gep13** [comment]
>@ferventcoder said...
BOM may not be there if the encoding is UTF-8 w/out BOM (and that is actually preferred).

I'll be honest, I don't fully understand the difference :smile:  I just remember it causing a problem, and thought I would note it as something to check for :smiley:

**Comment by gep13** [comment]
>@ferventcoder said...
This is probably going to end up in a note, unless you can think of a way to detect (perhaps if url includes x86 or 32). Then we could also add a note.

Nothing immediately springing to mind, nothing reliable anyway, so yeah, perhaps best as a Note.

**Comment by aronovgj** [comment]
> Not a package duplicating another existing package

this is not a reliable strategy but you could compare with packages having the same projectUrl, downloadUrl and the like and then give a warning.

**Comment by ferventcoder** [comment]
@aronovgj that one requires more thought definitely. :)

**Comment by gep13** [comment]
@ferventcoder are any of the rules that are left unchecked here needed for 0.1.0?  If not, I think we can break them into their own issue, and get this one closed out.  Thoughts?

**Comment by ferventcoder** [comment]
Agreed.
