### ISSUE TITLE
Note: Chocolatey Dependency

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-validator#33]
Unless a package needs a specific version of Chocolatey in order to function, a dependency on the Chocolatey Package is not required.

Add this as a note so that a human can verify.

**Comment by ferventcoder** [comment]
Sounds good.

We could also do a requirement if the choco version is lower than a certain number?

**Comment by ferventcoder** [comment]
Maybe not. Just a note

**Comment by ferventcoder** [comment]
We may need to ensure that items are actually flagged. You can do that by picking a package you know would fail and changing the search to look specifically for it.

**Comment by ferventcoder** [comment]
Or write a spec to pass a mocked IPackage that will return some dependencies - this is probably the better route.

**Comment by gep13** [comment]
@ferventcoder created issue to cover this: https://github.com/chocolatey/package-validator/issues/52
