### ISSUE TITLE
Guideline: Deprecated in title should be specified first and have a space between it and something else

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/package-validator#59]
[Deprecated]ServiceControl.install

**Comment by gep13** [comment]
@ferventcoder are the [ ]'s part of the requirement as well?

Related to this, and potentially another issue, should there be no files in the package?

**Comment by ferventcoder** [comment]
I think so - I like it written as `[Deprecated]`. You?

**Comment by ferventcoder** [comment]
Hmm, I wonder if there are two kinds of deprecations?

**Comment by ferventcoder** [comment]
For the kind I'm thinking of, when you deprecate a package, you remove all files and point to the dependency of the other. #60 is the dependency check.

**Comment by ferventcoder** [comment]
It may make sense to throw a note or a guideline related to files still in the package.

**Comment by ferventcoder** [comment]
Closed via #69
