### ISSUE TITLE
Ensure that the package being pulled for review isn't the one you just reviewed

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/package-validator#62]
https://chocolatey.org/packages/sbt/0.13.9

**Comment by ferventcoder** [comment]
Related to https://github.com/chocolatey/package-verifier/issues/28

**Comment by gep13** [comment]
@ferventcoder milestone?

**Comment by ferventcoder** [comment]
Logic bug in the random selector - if there is only one package it might get selected twice in a row.
