### ISSUE TITLE
Wiki Contributions

### ISSUE THREAD

**Issue by wjk** [chocolatey/package-validator#64]
I’ve noticed that almost all of the wiki pages are empty stubs at this point. I also noticed that editing for the package validator wiki is disabled. Is it possible to set up a separate wiki repo [like this one](https://github.com/chocolatey/choco-wiki)? If one is set up, I might be interested in supplying some preliminary documentation for the validator messages. Thanks!

**Comment by ferventcoder** [comment]
@wjk That would be fantastic.

**Comment by ferventcoder** [comment]
I've unlocked it for now - I will relock it later.

**Comment by ferventcoder** [comment]
Hope you can get started.

**Comment by gep13** [comment]
@wjk thanks for the offer of help! Any assistance that you can provide would be greatly appreciated! :+1:
