### ISSUE TITLE
Requirement: Packages should not contain git repositories

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-validator#72]
https://chocolatey.org/packages/StrawberryPerl/5.20.2.1

**Comment by gep13** [comment]
@ferventcoder do you agree that this is a requirement?

**Comment by ferventcoder** [comment]
@gep13 we already did this one.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/package-validator/blob/master/src/chocolatey.package.validator/infrastructure.app/rules/SourceControlInternalFilesAreNotPackagedRequirement.cs

**Comment by gep13** [comment]
Doh! Sorry, hadn't seen this one :smile:
