### ISSUE TITLE
Non-Versioned Dependency False Alarm

### ISSUE THREAD

**Issue by wjk** [chocolatey/package-validator#84]
I have just pushed an update to [the bfg-repo-cleaner package](https://chocolatey.org/packages/bfg-repo-cleaner/1.12.5) that addressed, among other things, the lack of a version constraint in the nuspec. However, following the update, the validator still flags the use of an non-versioned dependency. Please see attached screenshots.

![guidelines](https://cloud.githubusercontent.com/assets/1915951/11922822/c685abfc-a768-11e5-9d4e-8b09d05362c0.png)
![versioned-dependency](https://cloud.githubusercontent.com/assets/1915951/11922825/c9858cb4-a768-11e5-9c67-464b16db81c4.png)

**Comment by ferventcoder** [comment]
Likely a bug...

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/package-validator/blob/a5ba39c3daf0a19ed71c6624dd1f098ffe1454b4/src/chocolatey.package.validator/infrastructure.app/rules/DependencyWithNoVersionGuideline.cs#L29

Hmmm. We do have some specs for this one...maybe not enough.

**Comment by ferventcoder** [comment]
@wjk it was due to the spec not covering the scenario of only having a minimum version specified. Also to our misunderstanding of what that scenario would look like (we thought we were covering that scenario). I updated the specs to show this scenario and then fixed the code. See the linked commit.
